[project]
name = "linear-regression-from-scratch"
version = "0.1.0"
requires-python = ">= 3.9.0"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.3",
]
